FROM eclipse-temurin:17

ADD https://github.com/gitbucket/gitbucket/releases/download/4.41.0/gitbucket.war /opt/gitbucket.war

RUN ln -s /gitbucket /root/.gitbucket

VOLUME /gitbucket

EXPOSE 8080 29418

CMD ["sh", "-c", "java -jar /opt/gitbucket.war"]

FROM gitbucket/gitbucket:latest

COPY lib/*.jar /gitbucket/lib/