version: '3'

services:
  gitbucket:
    image: gitbucket/gitbucket
    container_name: gitbucket
    depends_on:
      - mysql-gitbucket
    volumes:
      - ./data/conf/gitbucket/database.conf:/gitbucket/database.conf
    environment:
      - JAVA_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=debug
    ports:
      - "8080:8080"
    networks:
      - gitbucket-network

  mysql-gitbucket:
    image: mysql:8.0
    container_name: mysql-gitbucket
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: gitbucket
      MYSQL_USER: gitbucket
      MYSQL_PASSWORD: 123123
    networks:
      - gitbucket-network

networks:
  gitbucket-network:
    name: gitbucket-network